@startuml
Entity Продукт {
Название
Количество
Срок годности
Уровень, при котором нужно сделать заказ
Поставщик
Склад
}

Entity Поставщик{
Название
Адрес
Телефон 
email
контактное лицо
}
 

Entity Пользователь {
Имя
Фамилия
Доступ 
email
Телефон
Пароль
}

Enum Типы_доступов {
Тип доступа
Доступные действия
}

Entity Заказ_поставщику {
Дата заказа
Поставщик
Статус
Общая стоимость
Список продуктов
Склад доставки
}


Entity Заказ_в_ресторане {
Дата заказа
Клиент 
Статус заказа
список заказанных блюд
Общая стоимость

}
Enum Статус_заказа_в_ресторане {
Оформлен
Оплачен
Готов
Отменен
}

Entity Технологическая_карта {
Наименование блюда
Список необходимых продуктов
Инструкция по приготовлению
Время приготовления

}
Enum Типы_продуктов {
Название
Описание
}

Entity Склад {
Наименование склада
Адрес
Максимальная емкость
Текущая загрузка
}
Entity Инвентаризация {
Дата инвентаризации
Пользователь
Список продуктов 
Комментарии 
}

Enum Статус_заказа {
  Новый
  Утвержден
  Оплачен
  В пути
  Доставлен
}

Продукт *--"1,*" Поставщик
Инвентаризация o-- Продукт
Заказ_поставщику "0..*" --> "1..*" Продукт
Пользователь "*" --> "1" Типы_доступов

Продукт "*" --> "1" Типы_продуктов

Продукт "0..*" --> "1..*" Технологическая_карта

Заказ_поставщику "0..*" --> "1..*" Склад
Заказ_в_ресторане "1..*" --> "0..*"  Технологическая_карта

Заказ_поставщику"0..*" --> "1..*"Поставщик

Заказ_поставщику "*" --> "1" Статус_заказа
Заказ_в_ресторане "1..*" --> "1..*" Продукт
Склад "1" --> "1..*" Продукт
Статус_заказа_в_ресторане "*" --> "1" Заказ_в_ресторане
Инвентаризация "0..*" --> "1..*" Пользователь
@enduml