@startuml
left to right direction

actor "Менеджер по ассортименту" as MS
actor "Менеджер пополнения" as MP
actor Технолог as T
actor "Система заказа" as R
rectangle Заказ {

usecase "Автозаказ продуктов" as AP
usecase "Утвердить список продуктов" as AP0

usecase "Внести правки" as AP1
usecase "Удалить заказ" as AP2
usecase "Отправить заказ" as AP3
usecase "Получить заказ" as AP4


usecase "Ручной заказ продуктов" as RZ
usecase "Собрать заказ" as RZ1


}
rectangle "Работа с продуктами"  {
usecase "Просмотреть наличие продуктов" as PP


usecase "Контроль срока годности" as KS
usecase "Просмотреть информацию о сроках годности" as KS1
usecase "Списать продукт" as KS2
usecase "Потратить продукт" as KS3


usecase "Инвентаризация" as UC1
usecase "Добавить продукт" as UC2
usecase "Удалить продукт" as UC3
usecase "Обновить информацию о продукте" as UC4
usecase "Просмотреть информацию о продукте" as UC6
}

rectangle "Работа с правами"  {
usecase "Регистрация пользователя" as UR1
usecase "Аутенфикация пользователя" as UR2
}

MS-->PP
MS-->UR1
MS-->UR2



T-->AP
T-->RZ
T-->UR1
T-->UR2
T-->KS

MP-->AP
MP-->KS 
R-->KS3
MP-->UC1
MP-->RZ
MP-->UR1
MP-->UR2

AP<--AP0 #line.dashed; :include
AP<--AP2 #line.dashed; :extend
AP0<--AP1 #line.dashed; :extend
AP0<--AP3 #line.dashed; :include
AP3<--AP4 #line.dashed; :include


KS<--KS1#line.dashed; :include 
KS1<--KS2#line.dashed; :include


UC1<--UC6 #line.dashed; :include 
UC6<--UC4 #line.dashed; :extend
UC6<--UC2#line.dashed; :extend
UC6<--UC3#line.dashed; :extend



RZ<--RZ1 #line.dashed; :include
RZ1<--AP2 #line.dashed; :extend
RZ1<--AP1 #line.dashed; :extend
RZ1<--AP3 #line.dashed; :extend
@enduml