site_name: Требования к системе

nav:
  - Домашняя страница:
    - index.md
  - Документация:
    - glossary.md
    - general info.md
    - goals.md
    - characteristics.md
    - business process.md
    - requirements.md
    - model.md
    - architecture.md