site_name: Требования к системе
site_url: https://kapustinaanna.github.io/site/
plugins:
  - render_swagger

nav:
  - Домашняя страница:
    - index.md
  - Документация:
    - glossary.md
    - general info.md
    - goals.md
    - characteristics.md
    - business process.md
    - requirements.md
    - model.md
    - architecture.md
    - uiux.md
    - api.md
  - Задачи:
    - tasks/add_product.md
    - tasks/update_product.md
    - tasks/info_product.md
    - tasks/product_write_off.md
    - tasks/product_issuance.md
    - tasks/expiration_date_control.md
    - tasks/autozakaz_product.md
    - tasks/zakaz_product.md 
    - tasks/inventory.md
    - tasks/auth_user.md 

    