 @startuml
Enum Продукт {
Название
Количество
Срок годности
Уровень, при котором нужно сделать заказ
Поставщик
}

Entity Поставщик{
Название
Адрес
Телефон 
email
контактное лицо
}
 

Entity Пользователь {
Имя
Фамилия
Доступ 
email
Телефон
Пароль
}

Enum Типы_доступов {
Тип доступа
Доступные действия
}

Entity Заказ_поставщику {
Дата заказа
Поставщик
Статус
Общая стоимость
Список продуктов
Склад доставки
}


Entity Заказа_в_ресторане {
Дата заказа
Пользователь 
Статус
список заказанных блюд
Общая стоимость

}

Entity Технологическая_карта {
Наименование блюда
Список необходимых продуктов
Инструкция по приготовлению
Время приготовления

}
Enum Типы_продуктов {
Название
Описание
}
Enum Очередь_на_выдачу {
Название продукта
Срок годности
}
Entity Склад {
Наименование склада
Адрес
Максимальная емкость
Текущая загрузка
}
Entity Инвентаризация {
Дата инвентаризации
Пользователь
Список продуктов 
Комментарии 
}
Entity Бронь_продуктов_для_роботов {
Продукт
Количество
Заказ
}
Enum Статус_заказа {
  Новый
  Утвержден
  Оплачен
  В пути
  Доставлен
}

Продукт *--"1,*" Поставщик
Инвентаризация o-- Продукт
Заказ_поставщику "0..*" --> "1..*" Продукт
Пользователь "*" --> "1" Типы_доступов
Продукт "*" --> "1" Типы_продуктов
Продукт "1..*" --> "0..* " Бронь_продуктов_для_роботов
Продукт "0..*" --> "1..*" Технологическая_карта
Продукт "1..*" --> "0..* " Очередь_на_выдачу
Заказ_поставщику "0..*" --> "1..*" Склад
Заказа_в_ресторане "1..*" --> "0..*"  Технологическая_карта
Технологическая_карта "1..*" --> "1..*" Бронь_продуктов_для_роботов
Заказ_поставщику"0..*" --> "1..*"Поставщик
Бронь_продуктов_для_роботов "1..*" --> "0..*"Очередь_на_выдачу
Заказ_поставщику "*" --> "1" Статус_заказа
Заказа_в_ресторане "1..*" --> "1..*" Продукт
@enduml
